### ISSUE TITLE
-1 API is missing img_url data

### ISSUE THREAD

**Issue by prastut** [prastut/bubble-frontend#11]
This is what I am getting when I run 

https://api.bubble.social/get-index-data?instance_id=a2932ab6-5f50-11e7-ba85-0669e02bb0da&channel=germany&start_timestamp=-1

```
{
  "data": "{\"pos\": 1.2991937526235717, \"neg\": 0.2924338271919916, \"pos_count\": 92, \"neg_count\": 27}", 
  "germany": {
    "neg": 0.2924338271919916, 
    "neg_count": 27, 
    "pos": 1.2991937526235717, 
    "pos_count": 92
  }, 
  "id": "Mon, 03 Jul 2017 11:51:03 GMT", 
  "time": 1499082663
}
```

**Comment by harwee** [comment]
Get index data wont return any metadata , of the channel, all the meta data of channel is available at get match details.

**Comment by prastut** [comment]
@harwee you are right. My bad.
