### ISSUE TITLE
A lot of metadata is missing in trending

### ISSUE THREAD

**Issue by prastut** [prastut/bubble-frontend#12]
https://api.bubble.social/get-trending-players?instance_id=a2932ab6-5f50-11e7-ba85-0669e02bb0da

^ Check this:

Sab zero aa raha hai and there is no metadata like given in the API documentation:
```
"trending":[
    {
        "htcu11":{
            "img_url":"",
            "keywords":[
                "#HTCU11"
            ],
            "name":"HTCU11",
            "neg_sum":0.7116224227409492,
            "pos_sum":26.548326577501577,
            "team":"team_a",
            "total_tweets":755,
            "type":"player"
        }
    }
]

```

**Comment by harwee** [comment]
Data returned has zero values because, they are zeros, nothing wrong with that. Will sort out  other problems
