### ISSUE TITLE
Unify IDE

### ISSUE THREAD

**Issue by prastut** [prastut/bubble-frontend#22]
Since we have more developers working now on codebase, how do we unify IDE's? What would be the best approach? Otherwise we would be running into unnecessary code changes. 

I am using VS Code as of now. Would recommend switching to it for JS development, primarily because of deep integration of jslint as well as intellisense. But won't fixate, since everybody has their own comfort zone with their editor. 

@digi0ps @jeremyphilemon you guys have a lot of production ready practises on uniqna. Let us know what can be done.

**Comment by digi0ps** [comment]
Uh, I don't think switching IDEs is a good idea. I have been using Sublime from the beginning and gotten accustomed to it. 

I don't think linting should be an issue. We can use the `eslint` npm package for that purpose. 
eslint has plugins for Sublime, Atom and VS Code.
Also, we can write a *npm run* command to check for linting errors before a commit.

**Comment by prastut** [comment]
> But won't fixate, since everybody has their own comfort zone with their editor.

I agree. What about indentation errors? Some follow space, or tabs, and some have different settings for how many tabs are equal to a space etc, etc. 

^ VS Code automatically indents code after each save so I was wondering whether it would create a problem.

**Comment by digi0ps** [comment]
We can make sure everyone uses either space or tab with the lint options? Sublime highlights linting errors for me while typing. ESLint can use some famous predefined set of lint rules from Google/Airbnb. It's completely customisable. Check it out maybe? [ESLint](http://eslint.org/docs/user-guide/getting-started)

**Comment by harwee** [comment]
> I agree. What about indentation errors? Some follow space, or tabs, and some have different settings for how many tabs are equal to a space etc, etc.

Well almost every IDE has a setting to specify how to intend i.e four spaces or a tab so decide on one then it's not a problem

**Comment by prastut** [comment]
Agree with @harwee. Closing this.
