### ISSUE TITLE
fix image alignment

### ISSUE THREAD

**Issue by arihantparsoya** [prastut/bubble-frontend#32]
From what I observe, the images are not correctly fitting in the circle and leaving empty space inside the circle.
 
![screen shot 2017-08-08 at 19 04 35](https://user-images.githubusercontent.com/15258498/29074252-32b7a72e-7c6c-11e7-824f-35203ea14561.png)

**Comment by prastut** [comment]
They are fixed here:
http://prastutkumar.design/idc-work-viz/?work

I wanted all of you who are getting upto speed to fix it.

**Comment by digi0ps** [comment]
The images look fine to me?
![image](https://user-images.githubusercontent.com/3889675/29131190-b937ceae-7d49-11e7-9fb1-5ead804a4614.png)

**Comment by prastut** [comment]
@digi0ps you were late to the party. Already fixed.
