### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by harwee** [prastut/bubble-frontend#52]
> npm install --python=python2.7

Use Python 3.6 for all use cases which require Python

**Comment by harwee** [comment]
> If you get node-gyp errors in installation, check the error log. Most probably your default python environment flag has been changed to v3 instead of 2.7. JsDOM (one of the dev dependencies) has an internal dependency on node-gyp which requires python2.7 to compile. Run the following to ensure proper installation:


My default Python Version is 3.6 and it compiled fine enough I guess,

**Comment by prastut** [comment]
It was an explicit error inside my installation therefore mentioned it.

**Comment by harwee** [comment]
Wont be a problem I guess, if it didn't compile with 3 for you, just use 2, this is a stupid issue though.
